############## START

### Note that numbers (e.g. 1.4) refer to sections of the edgeR vignette PDF

# Load deseq2 and set working directory
library(edgeR)
setwd("/directory/htseq_counts")  # Directory should contain the counts file generated by cluster_read_counts -> clustered_read_counts_combine

# Load in data
countData = as.matrix(read.table(file='combined.htseq.counts', header = TRUE, sep = "\t", stringsAsFactors = FALSE, row.names="gene_id"))
head(countData)

# Create DGEList data class (2.5)
group <- c("AR","DW","GH1","LS","OF","STP1","STP2","STP11A","STP12B","STP13A","STP15C","WS")  # Should be in the same order as the columns in the htseq.counts file
dgedata <- DGEList(counts=countData, group=group)

# Filter low count genes (based on 4.2.4, this will result in keeping genes with at least 1 count per million in at least 1 sample)
keep <- rowSums(cpm(dgedata)>1) >= 1
dgedata <- dgedata[keep, , keep.lib.sizes=FALSE]

# Perform TMM normalisation (4.1.4)
dgedata <- calcNormFactors(dgedata)

# Feed in a basic dispersion estimate to allow DE analysis (has no effect on outcome since we're using logfc rather than E-values/FDRs)
dgedata$common.dispersion <- 0.1

# Perform the DE analysis for each pair-wise sample (12 vs 12)
setwd("/directory/edger_output")
de_list = ""
N = 12
for(i in 1:(N-1)) {
  for(x in (i+1):N) {
    # Run DE      ###print(paste(i,x))
    tempDe = exactTest(dgedata, pair=c(i,x))
    # Put results into list
    de_list = c(de_list, tempDe)
  }
}

# Clean up after DE
de_list[1] <- NULL

# Save workspace to resume run from here on
save.image("revised_edgeR_de_complete.Rdata")
#load(file="revised_edgeR_de_complete.Rdata")     # Can comment out above, and uncomment this if you need to re-run the last step and modify logFC cut-offs / etc.

# Extract DE genes for each sample
for(i in seq(from=1, to=length(de_list),by=3)) {
  temp.de <- de_list[i:(i+2)]
  class(temp.de) <- "DGEExact"
  # Produce output file
  tTags = topTags(temp.de, n=NULL)
  deTags = subset(tTags[[1]], logFC <= -5 | logFC >= 5)
  write.csv(deTags, file=paste(paste(temp.de[[2]],collapse=".vs."),".edgeR.DE_results.csv", sep=""))
}

